#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

FILE="$1"

while read -r NUMBER; do

    factors=($)factor "$NUMBER"))

    factor1=${factors[-2]}
    factor2=${factors[-1]}

    echo "$NUMBER=$factor1*$factor2"
done < "$FILE"
