#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "USAGE: $0 <FILE>"
    exit 1
fi

FILE="$1"

while read -r NUMBERS; do

    factors=($(factor "$NUMBERS"))

    factor1=${factors[-2]}
    factor2=${factors[-1]}

    echo "$NUMBERS=$factor1*$factor2"
done < "$FILE"
