#!/bin/bash

is_prime()
{
	num=$1
	if [ "$num" -lt 2 ]; then
		return 1
	fi
	for ((i=2; i*i<=num; i++)); do
		if [ "$((num % i))" -eq 0 ]; then
			return 1
		fi
	done
	return 0
}

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <file>"
	exit 1
fi

FILE="$1"

while read -r NUMBERS; do

	if ! [[ "$NUMBERS" =~ ^[2-9][0-9]*$ ]]; then
		echo "Invalid input: $NUMBERS. Skipping..."
		continue
	fi

	factors=()
	for ((i=2; i<=NUMBERS; i++)); do
		if [ "$((NUMBERS % i))" -eq 0 ] && is_prime "$i"; then
			factors+=("$i")
			while [ "$((NUMBERS % I))" -eq 0 ]; do
				NUMBERS=$((NUMBERS / i))
			done
		fi
	done

	if [ "${#factors[@]}" -eq 2 ]; then
		echo "$NUMBERS=${FACTORS[0]}*${FACTORS[1]}"
	else
		echo "Unabale to factorize $NUMBERS into two prime numbers"
	fi
done < "$FILE"
